apiVersion: 1

datasources:
#   # <string, required> name of the datasource. Required
  - name: Graphite
    type: graphite
    # <string, required> access mode. direct or proxy. Required
    access: proxy
    orgId: 1
    url: GRAPHITE_URL
    basicAuth: true
    basicAuthUser: guest
    basicAuthPassword: guest
    isDefault: true
    # <map> fields that will be converted to json and stored in json_data
    jsonData:
       graphiteVersion: "1.0"
       tlsSkipVerify: true
#      tlsAuth: true
#      tlsAuthWithCACert: true
#   # <string> json object of data that will be encrypted.
#   secureJsonData:
#     tlsCACert: "..."
#     tlsClientCert: "..."
#     tlsClientKey: "..."
    version: 1
#   # <bool> allow users to edit datasources from the UI.
    editable: true

